language: java

matrix:
   include:
      - jdk: openjdk8
         env: MAVEN_ARGS="-Pjacoco coveralls:report"
      - jdk: openjdk9
        if: type IN (pull_request)
      - os: osx
        osx_image: xcode 10.1
        if: type IN (pull_request)

#skip installation step
install: true

cache:
   directories:
      - $HOME/.m2

script:
   - mvn -f helloproject/pom.xml clean verify $MAVEN_ARGS