language: java

matrix:
   include:
      - jdk: openjdk8
      - jdk: openjdk9
         if: type IN (pull_request)
      - os: osx
        osx_image: xcode 10.1
        if: type IN (pull_request) OR commit_message =~ /^Merge pull request/

#skip installation step
install: true

cache:
   directories:
      - $HOME/.m2

script:
   - mvn -f helloproject/pom.xml clean verify -Pjacoco coveralls:report