language: java

jdk: openjdk9
#matrix:
#   include:
#      - jdk: openjdk9
#      - jdk: openjdk9
#      - os: osx
#        osx_image: xcode 10.1
#        if: type IN (pull_request)

#skip installation step
install: true

cache:
   directories:
      - $HOME/.m2

script:
   - mvn -f helloproject/pom.xml clean verify -Pjacoco coveralls:report